### ISSUE TITLE
blur implementation 

### ISSUE THREAD

**Issue by Only-Moon** [NoCymer/NEXXT-Tabs#2]
This is a perfect extension and I tried it today and switched full-time to it. one thing I want to be added is the blur/ transparency.

People switched to this extension because they don't like their default grey look and here, they are getting grey color for the bookmark background and on the search bar.

you can make the search bar area transparent

**Comment by NoCymer** [comment]
Fully implemented in commit [816d045](https://github.com/NoCymer/nexxt-tabs/commit/816d045633a94362aa7f254de90336aa09845e8e)

**Comment by Only-Moon** [comment]
When will it be out to use?

**Comment by Xx-Mohit-xX** [comment]
When will it be out to use?

**Comment by NoCymer** [comment]
> When will it be out to use?

Difficult to say, if everything goes well maybe in a few weeks, but i prefer not to give absolute deadlines out of thin air so take this estimation with a grain of salt.
