### ISSUE TITLE
nexxt-tabs showing one piece releasing on Wednesday

### ISSUE THREAD

**Issue by Only-Moon** [NoCymer/NEXXT-Tabs#3]
![Screenshot 2023-06-07 123846](https://github.com/NoCymer/nexxt-tabs/assets/75924613/28c00fe3-d4a9-4055-aa74-b17963762020)

Everyone knows one piece releases its episode on Sunday but the anime release page shows its release on Wednesday.

The rest of the series seems good to me, it's just one piece that shows on a wrong day

**Comment by NoCymer** [comment]
Which version are you on ?

**Comment by Only-Moon** [comment]
its V2.1 in info section

**Comment by NoCymer** [comment]
It has been fixed in version 3.0 which will be available later on.
