### ISSUE TITLE
how to get v3.3 update

### ISSUE THREAD

**Issue by Only-Moon** [NoCymer/NEXXT-Tabs#5]
It's showing version 2.1 on the chrome store.

so how do I get it?

**Comment by NoCymer** [comment]
You need to wait a little more :), it's currently under review for publish, in around a week it will be available

**Comment by Only-Moon** [comment]
Your hard work, dedication, and passion in developing this project have made a significant impact. Your skills and talents are truly commendable, and I deeply appreciate your efforts. Keep up the outstanding work!

**Comment by Only-Moon** [comment]
it's still on v2.1 on Chrome web store

**Comment by NoCymer** [comment]
Had a few issues with chrome web store,  it will be available today if everything goes right.

**Comment by NoCymer** [comment]
> Had a few issues with chrome web store, it will be available today if everything goes right.

Due to unforseen bug, the release is currently not working properly, if it happens to you please just re-install the extension, it should fix it, the hotfix is on its way but needs to get approved first.

**Comment by Only-Moon** [comment]
Alright thanks, I'll check it out. Also why dont you add it to Microsoft Edge Extension Store as well, it basically a port of chrome and chrome Extensions work on edge but adding on edge store will help you reach more audience

**Comment by NoCymer** [comment]
> Alright thanks, I'll check it out. Also why dont you add it to Microsoft Edge Extension Store as well, it basically a port of chrome and chrome Extensions work on edge but adding on edge store will help you reach more audience

Thanks for the suggestion, i'll look into it.
Also the hotfix is now live, if you have the time, feedbacks are welcome :)

**Comment by Only-Moon** [comment]
I got v3.3.1 and why there are no anime backgrounds? the whole reason I used this was coz of those auto-updated anime backgrounds and they are gone now. it now has 4 landscapes

just why?

**Comment by NoCymer** [comment]
The whole reason why there are no more anime backgrounds is long so i'm gonna break it in 3.

The main one being that in its current state the extension only targeted a niche of people that is anime fans and it was just the next logical step to broaden the targeted audience.

The second reason is that while the extension would grow the package size still would also grow we already were at a steady 10+mb of backgroud per update it would have grown to unreasonable sizes if backgrounds were still added.

The last reason was that one of the main goal of NEXXT Tabs was to provide a customized experience for every customer, which is now achived through the addition of customized backgrounds,  now each person can decide whether they want their tab anime themed, nature themed, or whatsoever.

I understand that this decision was a bold move and that it will displease the people that were here for the anime, but there still are anime related feature such as the schedule. Whilst one might love the fact that its now at the customer's charge to import background, one might also hate that its now no more a "bundle" of backgrounds.

Hope that this answers your question, if you have anything to ask i'm all ears.

Have a nice day,
NoCymer

**Comment by Only-Moon** [comment]
I understand your point, but at least add a feature to have backgrounds from a URL, this way we can use the API to use whatever background we have. there is an extension that does the same, I'll link it up: https://chrome.google.com/webstore/detail/nextab/onohmogbflopjcbaglmbagpbjehaacpf

**Comment by NoCymer** [comment]
> I understand your point, but at least add a feature to have backgrounds from a URL, this way we can use the API to use whatever background we have. there is an extension that does the same, I'll link it up: https://chrome.google.com/webstore/detail/nextab/onohmogbflopjcbaglmbagpbjehaacpf

I dont quite understand what you meant, in the new version you can add your backgrounds, there is a button for that. Or did you mean adding a feature to this background add system to allow url background import?

**Comment by Only-Moon** [comment]
yeah add background import from url, so I can use API such as https://pic.re/image and have an anime background, you can also make it do a prefetch (auto update) after a certain time, as it used to past in previous versions
or bring the previous anime background part and make it optional like they will have that auto-update anime wallpapers or they can use custom wallpapers

it has that anime schedule section so most of the people using it anime watches as that part is of no use for non-anime watchers

**Comment by NoCymer** [comment]
I really would want to help you but i dont understand your input.

**Comment by Only-Moon** [comment]
![image](https://github.com/NoCymer/nexxt-tabs/assets/75924613/625b6dd4-89a7-4e15-9d5f-86d6ca94707c)
like this from the extension i mentioned above.

what it does is instead of uploading an image to be used as background it gives us the option to use an image URL, from example I entered the API which I mentioned above (it outputs a random image everytime) gives an image and I can use that image from URL as background
