### ISSUE TITLE
Extension is broken

### ISSUE THREAD

**Issue by Only-Moon** [NoCymer/nexxt-tabs#8]
if you still have plans to work on it then kindly check the extension as the tab page is completely broken.

sharing two images, one at 100% zoom and one at 25%
![Screenshot 2024-10-17 181524](https://github.com/user-attachments/assets/d2ac1e59-00c1-4c0a-bc5a-b952e1ef6789)
![Screenshot 2024-10-17 181618](https://github.com/user-attachments/assets/5a00add0-aceb-468f-835f-a319e22da324)

**Comment by NoCymer** [comment]
Can you provide more information about the issue (browser version, extension version, when does the problem occurs) Also do you have any other extension that may modify the look of web pages ?
